---
- hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer paquets nécessaires
      apt:
        name:
          - curl
          - git
          - nodejs
          - npm
          - docker.io
        state: present
        update_cache: yes

    - name: Ajouter utilisateur au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
